services:
  postgres:
    image: "postgres:15.4"
    container_name: btc-postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - .env
  web:
    build:
      context: .
    restart: always
    container_name: btc-web
    command: sh -c "python manage.py migrate &&
              gunicorn --bind 0.0.0.0:8000 brian_tambara_com.wsgi --workers=4"
    env_file:
      - .env
    volumes:
      - static_volume:/app/site_media/static
      - media_volume:/app/media
    expose:
      - "8000"
    depends_on:
      - postgres
      - nginx
  nginx:
    build: nginx
    container_name: btc-nginx
    restart: always
    volumes:
      - static_volume:/app/site_media/static
      - media_volume:/app/media
    ports:
      - "80:80"
volumes:
  media_volume:
  static_volume:
  db:
